name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main     

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /home/ec2-user/BE

      - name: Change ownership
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R ec2-user:ec2-user /home/ec2-user/BE

      - name: Go to project directory and pull latest code
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/BE
            git pull origin main

      - name: Install dependencies
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo yum update
            sudo yum install -y nodejs npm
            sudo npm install -g pm2 dotenv

      - name: Set environment variables
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/BE
            echo "USERNAME=${{ secrets.USERNAME }}" >> .env
            echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
            echo "DATABASE=${{ secrets.DATABASE }}" >> .env
            echo "NAVER_ID=${{ secrets.NAVER_ID }}" >> .env
            echo "NAVER_SECRET=${{ secrets.NAVER_SECRET }}" >> .env
            echo "NAVER_CALLBACK_URL=${{ secrets.NAVER_CALLBACK_URL }}" >> .env
            echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
            echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
            echo "KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }}" >> .env
            echo "NAVER_LOGIN_REDIRECT=${{ secrets.NAVER_LOGIN_REDIRECT }}" >> .env
            echo "KAKAO_LOGIN_REDIRECT=${{ secrets.KAKAO_LOGIN_REDIRECT }}" >> .env

      - name: Install project dependencies
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/BE
            npm ci

      - name: Restart server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo pm2 restart ohneul-server || sudo pm2 start npm --name ohneul-server -- start:dev

      - name: Check PM2 list
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo pm2 list
