name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Change permissions
        run: sudo su -

      - name: Checking root
        run: |
          pwd
          ls -al

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "20"

      # - name: Cache dependencies
      #   id: cache
      #   uses: actions/cache@v2
      #   with:
      #     path: "**/node_modules"
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # - name: Install dependencies
      #   run: |
      #     sudo apt update
      #     sudo apt install -y nodejs npm  
      #     sudo npm install -g pm2
      #     sudo npm install -g dotenv

      - name: Create a folder and move
        run: |
           sudo mkdir -p /home/ec2-user/BE
           sudo chown -R ec2-user:ec2-user /home/ec2-user/BE
           cd /home/ec2-user/BE


      - name: Go to project directory
        run: |
            pwd        
            cd /home/ec2-user/BE

      # - name: Setting .env
      #   run: |
      #     echo "USERNAME=${{ secrets.USERNAME }}" >> .env
      #     echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
      #     echo "DATABASE=${{ secrets.DATABASE }}" >> .env
      #     echo "NAVER_ID=${{ secrets.NAVER_ID }}" >> .env
      #     echo "NAVER_SECRET=${{ secrets.NAVER_SECRET }}" >> .env
      #     echo "NAVER_CALLBACK_URL=${{ secrets.NAVER_CALLBACK_URL }}" >> .env
      #     echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
      #     echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
      #     echo "KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }}" >> .env
      #     echo "NAVER_LOGIN_REDIRECT=${{ secrets.NAVER_LOGIN_REDIRECT }}" >> .env
      #     echo "KAKAO_LOGIN_REDIRECT=${{ secrets.KAKAO_LOGIN_REDIRECT }}" >> .env
      #     cat .env
      
      # - name: Remote
      #   run: git remote update

      # - name: Git pull
      #   run: git pull origin main

      # - name: Install project dependencies
      #   run: npm ci

      # - name: Restart server
      #   run: sudo pm2 restart ohneul-server || sudo pm2 start npm --name ohneul-server -- start:dev

      # - name: Checking Pm2 List
      #   run: sudo pm2 list

      # # - name: Checking server logs
      # #   run: |
      # #     sudo pm2 logs ohneul-server
      # #     sudo pm2 logs ***-server
