name: dist

on:
  push:
    branches: [ develop ]

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: SSH to EC2 instance and deploy
        uses: appleboy/ssh-action@v0.5.4
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd BE
            sudo git remote update
            sudo git pull origin develop
            sudo npm ci
            sudo npm run start:dev
            sudo pm2 restart ohneul-server

  # 깃허브 레파지토리가 프라이빗으로 만들어져 있을때. 
  # git pull https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PASSWORD }}@github.com/blockenters/streamlit_kmeans.git
 
